name: "Bl action"
description: "Github action for Blaxel, a platform for building and deploying AI agents"
author: blaxel
branding:
  color: "orange"
  icon: "bold"
inputs:
  workspace:
    description: "Blaxel workspace to deploy to"
    required: true
  apikey:
    description: "Blaxel API key"
    required: true
  deploy:
    description: "If you want to deploy to Blaxel, specify the path to the folder or the file you want to deploy"
    default: ""
    required: false
runs:
  using: "composite"
  steps:
    - name: Install blaxel
      shell: bash
      run: |
        mkdir -p $HOME/.local/bin

        if [ "$BL_ENV" = "dev" ]; then
          curl -fsSL https://raw.githubusercontent.com/blaxel-ai/toolkit/main/install.sh | BINDIR=$HOME/.local/bin sh
        else
          curl -fsSL https://raw.githubusercontent.com/blaxel-ai/toolkit/main/install.sh | BINDIR=$HOME/.local/bin sh
        fi
        cp $HOME/.local/bin/blaxel $HOME/.local/bin/bl
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: Login to Blaxel
      shell: bash
      env:
        BL_API_KEY: ${{ inputs.apikey }}
      run: bl login ${{ inputs.workspace }}
    - name: Deploy to Blaxel
      shell: bash
      if: inputs.deploy != ''
      run: bl apply -R -f ${{ inputs.deploy }}
