apiVersion: blaxel.ai/v1alpha1
kind: Function
metadata:
  name: github
  displayName: Github
spec:
  enabled: true
  policies: ["only-eu"]
  configuration:
    github_token:
      value: ${GH_PAT}
      secret: true
  storeId: "github"